### PR TITLE
Add Arc-based variants for each of the three themes

### PR DESCRIPTION
**Pull request by rayes0**

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Can you send some screenshots?

**Comment by rayes0** [comment]
Some previews for now. I haven't changed anything in the readme yet,  should I add some previews myself, or leave that to you?

**Dawn**

dawn

**Moon**

moon

**Normal**

normal

**Comment by ThatOneCalculator** [comment]
They look nice, but can you implement the title bars and buttons from the existing version?

**Comment by mvllow** [comment]
Is there anything we can help with @rayes0? We appreciate the work you've put into this and a lot of people would love to see this merged 🥰

**Comment by Ashe** [comment]
I would love to see this merged too! Only just discovered this colourscheme!

**Comment by ThatOneCalculator** [comment]
@rayes0 the buttons on the top don't matter too much, but we'd love to merge this! Can you re-open this PR?

**Pull request closed without merging**
