### PR TITLE
Add GTK4

### LINKED ISSUE #10: Add libadwaita theme and fix legacy theming
Following the release of libadwaita and its adoption in GNOME 42 this theme no longer works as expected on updated GNOME instances. 

### GTK 4
Theming within GTK 4 seems to be easier than ever with a single css file allowing for pretty extensive modifiactions of pretty much every part of the toolkit. A new set of themes could be released (I'm already working on one, though I'm not sure whether to base it on this repository or create a new one for gtk4).

### Regarding the legacy theme
As of now, the gtk-3 theme can still be used with GNOME Tweaks (as shown below).
image
However, if you're using GNOME in dark mode (which you probably are if you're using a dark them. e such as RP or RPM) the background colors are flipped. Example:
image
The workarounds for this issue could be either of these:

- refactoring the legacy (gtk-3) theme by changing the background color so that it gets flipped to the correct one
- creating the new GTK 4 theme as a light theme

Both of these aren't ideal and will be annoying for users to install and understand, but the latter seems doable.

### PR DESCRIPTION
**Pull request by ashbork**
Hi!
I managed to put together a libadwaita theme. The readme and releases will need to be updated if this PR gets merged, as I also changed the repo's structure according to @mvllow's recommendation. I'd be happy to help with that too.

### CODE REVIEW

**Comment by mvllow** [comment]
Unfortunately this is too large for me to review on both the web and local (both error out before I'm able to view anything). Maybe @ThatOneCalculator can chime in 😌

**Comment by ThatOneCalculator** [comment]
I'll have to test this out when I have the chance, thank you!

**Comment by ThatOneCalculator** [comment]
I'm looking at all the SVGs and everything on my phone, I've gotta say it looks like you did an incredible job! What did you use to make this @maybork ?

**Comment by ashbork** [comment]
If you mean the icons, they're the ones that are currently in the repo, I just moved them to keep it more organized, I wouldn't dare attributing them to myself! To be fair, that simple change does make it seem like I did a lot more than just moving files, sorry, I'm pretty new to Git.

Of course, the structure could be changed if you wish - I just thought that it'd be way easier to follow the installation steps with the files divided across directories, especially since GTK4 and libadwaita means that there's another step necessary if we want a consistent user experience. I'll leave that decision up to you, though!

As for the creation of the GTK4 theme, this was way easier through [the build tool](https://github.com/rose-pine/build) - otherwise, the process is just defining a bunch of colors. Replacing one's `~/.config/gtk-4.0/gtk.css` with one of the variants overrides the default libadwaita colors - no need for Tweaks. However, legacy apps still need a GTK3 theme (and you need to apply them through Tweaks).

**Comment by ThatOneCalculator** [comment]
I keep trying to review it :joy: 
image

**Comment by ThatOneCalculator** [comment]
From my testing it works great, I'll merge it for now and lyk if any more issues arise. Thank you for your work on this!

**Pull request merged**
