### PR TITLE
Add GNOME Shell theme

### LINKED ISSUE #8: Add shell theme
I have downloaded the theme in Gnome and applied it tho it does not have a gnome shell theme which just makes it looks bad. and I thought I might use Dracula but those 2 does not go well

### PR DESCRIPTION
**Pull request by ashbork**
The shell theme's author allowed for their theme to be used here! This resolves #8 (though not all variants are included yet but I'm sure that can be done fairly easily with [build](https://github.com/rose-pine/build).

### CODE REVIEW

**Comment by ashbork** [comment]
Wow this commit history is a mess, I tried squashing but that doesn't seem to have helped

**Comment by mvllow** [comment]
No worries on the commit history, we can squash on merge 😌 If @ThatOneCalculator has time I'll ask them to review the PR since I don't understand most of this gtk stuff 😭

**Comment by ashbork** [comment]
I don't quite understand it myself, it seems to just be css but it's generated somehow, I'd love to see a tool that'd do it more easily (I had to edit the files manually to change the things I didn't quite like)

**Comment by ThatOneCalculator** [comment]
I can't quite test it out since I don't use GNOME, it looks fine structurally, but I'll need to set up a VM/machine with GNOME to test it.

**Comment by mvllow** [comment]
> I can't quite test it out since I don't use GNOME, it looks fine structurally, but I'll need to set up a VM/machine with GNOME to test it.

That would be appreciated but don't feel like you need to 😌 If you want to merge as-is that's definitely fine too!

**Review by zoedsoupe — APPROVED** [review]

**Comment by mvllow** [comment]
Trusting @zoedsoupe approval because they like functional programming :)

**Comment by zoedsoupe** [comment]
Oh gosh, that's a huge responsibility haha

**Pull request merged**
