### PR TITLE
Add instruction for apply themes manually in GTK configuration file

### PR DESCRIPTION
**Pull request by ghost**
An instruction for users who prefer not to use a GUI software for changing GTK themes and icons.

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Will properly review in the morning, but I don't think settings for xsettingsd should be included now that most environments use Wayland instead of X11

**Comment by ghost** [comment]
xsettingsd instruction removed.

**Comment by ThatOneCalculator** [comment]
Instead of italicized instructions for GTK4, just say "For GTK4...", and/or use info blocks

> [!NOTE]
> Like this

**Comment by ghost** [comment]
Sounds good?

**Pull request merged**
