### PR TITLE
Simplify usage instructions

### PR DESCRIPTION
**Pull request by mvllow**
> I know close to nothing about GTK, so please close if this doesn't increase clarity

I think it is helpful to break out GTK3 and GTK4 usage instructions, even if duplicative. My understanding is that you would only be using GTK3 _or_ GTK4 so hopefully this separation is easier for the user.

_Unsure if the part about restarting your apps applies to both GTK3 and GTK4_

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Restarting is very situational. For wayland, you don't need to restart at all, and for X11, if `xsettingsd` is installed then restarts aren't required either.

> My understanding is that you would only be using GTK3 or GTK4 so hopefully this separation is easier for the user.

Maybe in 5 years... for now 80% of GTK apps are stuck on GTK3 :grin: So most people are using either both or just GTK3.

**Comment by mvllow** [comment]
Ah appreciate the info. I'll rethink this PR as I think the instructions could be a little less confusing.

**Comment by ashbork** [comment]
> Restarting is very situational. For wayland, you don't need to restart at all, and for X11, if `xsettingsd` is installed then restarts aren't required either.

I've had different experiences, I had to close and reopen any GTK4 apps for the theme to apply. Maybe that is what you meant and my wording in the readme is ambiguous. Sorry if that's the case, English isn't my first language.

Regarding GTK3 and 4, both are pretty much necessary right now - GNOME adopted libadwaita but not all of the apps are ported and it'll take months if not years for full adoption of the new toolkit.

**Comment by ThatOneCalculator** [comment]
I think we've had different experiences then. Keep in mind I'm on Hyprland, which handles things very differently from GNOME.

**Comment by mvllow** [comment]
Closing this to avoid micro-managing 😌 Thank you all for your contributions 💜

**Pull request closed without merging**
